truncate table dictionary;
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','公用', '删除状态','1000','有效', '0',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','公用', '删除状态','1000','删除', '1',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','公用', '是否启用','1008','启用', '100801',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','公用', '是否启用','1008','停用', '100802',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','APP', '消息状态','1020','收到', '102001',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','APP', '消息状态','1020','队列', '102002',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','APP', '消息状态','1020','发送', '102003',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','APP', '消息状态','1020','成功', '102004',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','APP', '消息状态','1020','取消', '102005',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','APP', '消息状态','1020','失败', '102006',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','APP', '消息大类','1021','SMS', '102101',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','APP', '消息大类','1021','EMAIL', '102102',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','APP', '消息小类','1022','SMS', '102201',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','APP', '消息小类','1022','EMAIL', '102202',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','APP', '邮件内容类型','1023','HTML', '102301',  '');
INSERT INTO `dictionary`(`created_by`, `enable`,`module`, `type_name`,`type_code`, `name`,`value`,`remark`)  VALUES (-1,'100801','APP', '邮件内容类型','1023','PLAIN', '102302',  '');