-- MySQL Script generated by MySQL Workbench
-- Thu Jun 20 10:54:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema starter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `dictionary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dictionary` ;

CREATE TABLE IF NOT EXISTS `dictionary` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `enable` VARCHAR(6) NOT NULL COMMENT '是否启用',
  `module` VARCHAR(20) NULL DEFAULT NULL COMMENT '所属模块',
  `type_name` VARCHAR(20) NULL DEFAULT NULL COMMENT '类别名称',
  `type_code` VARCHAR(20) NULL DEFAULT NULL COMMENT '类别代码',
  `name` VARCHAR(20) NULL DEFAULT NULL COMMENT '名称',
  `value` VARCHAR(20) NULL DEFAULT NULL COMMENT '值',
  `remark` VARCHAR(20) NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;


-- -----------------------------------------------------
-- Table `template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `template` ;

CREATE TABLE IF NOT EXISTS `template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
