-- MySQL Script generated by MySQL Workbench
-- Thu May 16 15:40:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema starter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authority` ;

CREATE TABLE IF NOT EXISTS `authority` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `name` VARCHAR(50) NOT NULL COMMENT '角色名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;

CREATE UNIQUE INDEX `UK_ authority_name` ON `authority` (`name` ASC);


-- -----------------------------------------------------
-- Table `dictionary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dictionary` ;

CREATE TABLE IF NOT EXISTS `dictionary` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `enable` VARCHAR(6) NOT NULL COMMENT '是否启用',
  `module` VARCHAR(20) NULL DEFAULT NULL COMMENT '所属模块',
  `type_name` VARCHAR(20) NULL DEFAULT NULL COMMENT '类别名称',
  `type_code` VARCHAR(20) NULL DEFAULT NULL COMMENT '类别代码',
  `name` VARCHAR(20) NULL DEFAULT NULL COMMENT '名称',
  `value` VARCHAR(20) NULL DEFAULT NULL COMMENT '值',
  `remark` VARCHAR(20) NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;


-- -----------------------------------------------------
-- Table `template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `template` ;

CREATE TABLE IF NOT EXISTS `template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人ID',
  `email` VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
  `enabled` BIT(1) NOT NULL COMMENT '是否启用',
  `last_login_date` DATETIME NULL DEFAULT NULL COMMENT '最后登录日期',
  `last_login_ip` VARCHAR(50) NULL DEFAULT NULL COMMENT '最后登录IP',
  `last_password_reset_date` DATETIME NOT NULL COMMENT '最后密码重置日期',
  `name` VARCHAR(50) NOT NULL COMMENT '姓名',
  `password` VARCHAR(100) NOT NULL COMMENT '密码',
  `username` VARCHAR(50) NOT NULL COMMENT '手机号/用户名',
  `onboard_date` DATE NULL DEFAULT NULL COMMENT '入职日期',
  `last_date` DATE NULL DEFAULT NULL COMMENT '离职日期',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;

CREATE UNIQUE INDEX `UK_user_username` ON `user` (`username` ASC);


-- -----------------------------------------------------
-- Table `user_authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_authority` ;

CREATE TABLE IF NOT EXISTS `user_authority` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `authority_id` BIGINT(20) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_user_authority_authority_id`
    FOREIGN KEY (`authority_id`)
    REFERENCES `authority` (`id`)
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_user_authority_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;

CREATE INDEX `IN_ user_authority_user_id` ON `user_authority` (`authority_id` ASC);

CREATE INDEX `IN_user_authority_authority_id` ON `user_authority` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `app`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app` ;

CREATE TABLE IF NOT EXISTS `app` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  `app_id` VARCHAR(50) NOT NULL COMMENT 'App ID',
  `app_security` VARCHAR(50) NOT NULL COMMENT 'App Security',
  `owner_email` VARCHAR(50) NULL COMMENT 'Owner Email',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT
COMMENT = 'Third Part APP Management';


-- -----------------------------------------------------
-- Table `app_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_message` ;

CREATE TABLE IF NOT EXISTS `app_message` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  `message_id` VARCHAR(50) NOT NULL COMMENT '消息ID，对外',
  `app_id` VARCHAR(50) NOT NULL COMMENT 'App ID',
  `mq_msg_id` VARCHAR(50) NULL COMMENT 'MQ Message ID',
  `receive_date` TIMESTAMP NULL COMMENT '消息到达接口时间',
  `queuing_date` TIMESTAMP NULL COMMENT '消息发布到MQ时间',
  `send_date` TIMESTAMP NULL COMMENT '消息请求发送时间',
  `cancel_date` TIMESTAMP NULL COMMENT '消息取消时间',
  `status` CHAR(6) NOT NULL COMMENT '状态',
  `reason` VARCHAR(200) NULL COMMENT '缘由',
  `message_class` VARCHAR(6) NOT NULL COMMENT '消息大类',
  `message_type` VARCHAR(6) NULL COMMENT '消息小类',
  `content` VARCHAR(500) NOT NULL COMMENT '消息内容',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT
COMMENT = '消息';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
