-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 22:27:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authority` ;

CREATE TABLE IF NOT EXISTS `authority` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `name` VARCHAR(50) NOT NULL COMMENT '角色名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `UK_ authority_name` ON `authority` (`name` ASC);


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人ID',
  `email` VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
  `enabled` BIT(1) NOT NULL COMMENT '是否启用',
  `last_login_date` DATETIME NULL DEFAULT NULL COMMENT '最后登录日期',
  `last_login_ip` VARCHAR(50) NULL DEFAULT NULL COMMENT '最后登录IP',
  `last_password_reset_date` DATETIME NOT NULL COMMENT '最后密码重置日期',
  `name` VARCHAR(50) NOT NULL COMMENT '姓名',
  `password` VARCHAR(100) NOT NULL COMMENT '密码',
  `username` VARCHAR(50) NOT NULL COMMENT '手机号/用户名',
  `onboard_date` DATE NULL COMMENT '入职日期',
  `last_date` DATE NULL COMMENT '离职日期',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `UK_user_username` ON `user` (`username` ASC);


-- -----------------------------------------------------
-- Table `user_authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_authority` ;

CREATE TABLE IF NOT EXISTS `user_authority` (
  `user_id` BIGINT(20) NOT NULL,
  `authority_id` BIGINT(20) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  CONSTRAINT `FK_user_authority_authority_id`
    FOREIGN KEY (`authority_id`)
    REFERENCES `authority` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_user_authority_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`))
ENGINE = InnoDB;

CREATE INDEX `IN_ user_authority_user_id` ON `user_authority` (`authority_id` ASC);

CREATE INDEX `IN_user_authority_authority_id` ON `user_authority` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `template` ;

CREATE TABLE IF NOT EXISTS `template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dictionary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dictionary` ;

CREATE TABLE IF NOT EXISTS `dictionary` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `enable` VARCHAR(6) NOT NULL COMMENT '是否启用',
  `module` VARCHAR(20) NULL COMMENT '所属模块',
  `type_name` VARCHAR(20) NULL COMMENT '类别名称',
  `type_code` VARCHAR(20) NULL COMMENT '类别代码',
  `name` VARCHAR(20) NULL COMMENT '名称',
  `value` VARCHAR(20) NULL COMMENT '值',
  `remark` VARCHAR(20) NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_program_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mini_program_user` ;

CREATE TABLE IF NOT EXISTS `mini_program_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `del_flag` CHAR(1)  NOT NULL DEFAULT '0' COMMENT '删除标志',
  `nick_name` VARCHAR(20) NULL DEFAULT NULL,
  `gender` SMALLINT(1) NULL,
  `language` VARCHAR(20) NULL DEFAULT NULL,
  `city` VARCHAR(20) NULL DEFAULT NULL,
  `province` VARCHAR(20) NULL DEFAULT NULL,
  `country` VARCHAR(20) NULL DEFAULT NULL,
  `avatar_url` VARCHAR(200) NULL DEFAULT NULL,
  `union_id` VARCHAR(100) NULL,
  `open_id` VARCHAR(100) NOT NULL,
  `join_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册日期',
  `column1` VARCHAR(50) NULL,
  `column2` VARCHAR(50) NULL,
  `phone` VARCHAR(20) NULL,
  `shop_id` BIGINT(20) NULL,
  `birthday` DATE NULL,
  `shop_name` VARCHAR(100) NULL COMMENT '店铺名称',
  `last_order_date` DATE NULL COMMENT '最近订单日期',
  `last_picture_date` DATE NULL COMMENT '最新拍照日期',
  `name` VARCHAR(100) NULL COMMENT '姓名',
  `status` VARCHAR(6) NULL,
  `order_count` BIGINT(20) NULL DEFAULT 0 COMMENT '订单数',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '客户信息'
PACK_KEYS = Default;

CREATE UNIQUE INDEX `open_id_UNIQUE` ON `mini_program_user` (`open_id` ASC);


-- -----------------------------------------------------
-- Table `user_mini_program_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_mini_program_user` ;

CREATE TABLE IF NOT EXISTS `user_mini_program_user` (
  `user_id` BIGINT(20) NOT NULL COMMENT '用户ID',
  `mini_program_user_id` BIGINT(20) NOT NULL COMMENT '小程序用户ID',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  CONSTRAINT `FK_User_Mini_User_ID`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_User_Mini_Mini_ID`
    FOREIGN KEY (`mini_program_user_id`)
    REFERENCES `mini_program_user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

CREATE INDEX `FK_User_Mini_User_ID_idx` ON `user_mini_program_user` (`user_id` ASC);

CREATE INDEX `FK_User_Mini_Mini_ID_idx` ON `user_mini_program_user` (`mini_program_user_id` ASC);


-- -----------------------------------------------------
-- Table `shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop` ;

CREATE TABLE IF NOT EXISTS `shop` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  `province_code` VARCHAR(45) BINARY NULL COMMENT '省份代码',
  `city_code` VARCHAR(45) NULL COMMENT '城市代码',
  `name` VARCHAR(100) NULL COMMENT '店铺名称',
  `address` VARCHAR(500) NULL COMMENT '店铺地址',
  `status` VARCHAR(6) NOT NULL COMMENT '营业状态',
  `longitude` DECIMAL(18,15) NULL COMMENT '经度',
  `latitude` DECIMAL(18,15) NULL COMMENT '纬度',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '店铺信息';


-- -----------------------------------------------------
-- Table `user_shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_shop` ;

CREATE TABLE IF NOT EXISTS `user_shop` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  `user_id` BIGINT(20) NULL COMMENT '职员ID',
  `shop_id` BIGINT(20) NULL COMMENT '店铺ID',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户店铺关系';


-- -----------------------------------------------------
-- Table `goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goods` ;

CREATE TABLE IF NOT EXISTS `goods` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  `img_url` VARCHAR(200) NULL COMMENT '商品照片URL',
  `identifier` VARCHAR(8) NULL COMMENT '商品编号',
  `name` VARCHAR(50) NULL COMMENT '商品名称',
  `spec` VARCHAR(10) NULL COMMENT '商品规格',
  `price` DECIMAL(10,2) NULL COMMENT '统一价格',
  `status` VARCHAR(6) NULL COMMENT '状态',
  `description` VARCHAR(500) NULL COMMENT '商品描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '商品';


-- -----------------------------------------------------
-- Table `shop_goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_goods` ;

CREATE TABLE IF NOT EXISTS `shop_goods` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  `shop_id` BIGINT(20) NOT NULL COMMENT '店铺ID',
  `price` DECIMAL(10,2) NOT NULL COMMENT '店铺价格',
  `goods_id` BIGINT(20) NOT NULL COMMENT '店铺ID',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '店铺在售商品';


-- -----------------------------------------------------
-- Table `guest_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guest_order` ;

CREATE TABLE IF NOT EXISTS `guest_order` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  `mini_user_id` BIGINT(20) NOT NULL COMMENT '客户ID',
  `order_date` DATE NULL COMMENT '订单日期',
  `goods_quantity` INT NULL COMMENT '商品数量',
  `total_amount` DECIMAL(10,2) NULL COMMENT '总金额',
  `discount_amount` DECIMAL(10,2) NULL COMMENT '优惠金额',
  `pay_amount` DECIMAL(10,2) NULL COMMENT '实付金额',
  `status` VARCHAR(8) NULL COMMENT '状态',
  `shop_id` BIGINT(20) NULL COMMENT '销售店铺',
  `sold_by` BIGINT(20) NULL COMMENT '销售人员ID',
  `shop_name` VARCHAR(100) NULL COMMENT '销售店铺',
  `sold_by_name` VARCHAR(50) NULL COMMENT '销售人员姓名 ',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '客户订单';


-- -----------------------------------------------------
-- Table `order_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_item` ;

CREATE TABLE IF NOT EXISTS `order_item` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  `img_url` VARCHAR(200) NULL COMMENT '商品照片URL',
  `identifier` VARCHAR(8) NULL COMMENT '商品编号',
  `name` VARCHAR(50) NULL COMMENT '商品名称',
  `spec` VARCHAR(10) NULL COMMENT '商品规格',
  `price` DECIMAL(10,2) NULL COMMENT '销售价格',
  `order_id` BIGINT(20) NULL COMMENT '订单ID',
  `quantity` INT NULL COMMENT '数量',
  `amount` DECIMAL(10,2) NULL COMMENT '金额',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '订单项目';


-- -----------------------------------------------------
-- Table `comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comment` ;

CREATE TABLE IF NOT EXISTS `comment` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  `mini_user_id` BIGINT(20) NULL COMMENT '客户ID',
  `shop_id` BIGINT(20) NULL COMMENT '店铺ID',
  `remark` VARCHAR(100) NULL COMMENT '职员备注',
  `remark_by` BIGINT(20) NULL COMMENT '备注人ID',
  `remark_date` TIMESTAMP NULL COMMENT '备注日期',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '客户备注';


-- -----------------------------------------------------
-- Table `photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `photo` ;

CREATE TABLE IF NOT EXISTS `photo` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `created_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人ID',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  `updated_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新人',
  `del_flag` CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
  `mini_user_id` BIGINT(20) NOT NULL COMMENT '客户ID',
  `shop_id` BIGINT(20) NOT NULL COMMENT '店铺ID',
  `photo_url` VARCHAR(200) NOT NULL COMMENT '照片URL',
  `taked_by` BIGINT(20) NULL COMMENT '拍照人ID',
  `taked_date` DATE NULL COMMENT '拍照日期',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '客户备注';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
